### PR TITLE
Use `std::thread::ThreadId` instead of custom thread id

### PR DESCRIPTION
**Pull request by Noratrieb**
`std` guarantees them to be [unique](https://doc.rust-lang.org/std/thread/struct.ThreadId.html), allowing us to use them here instead of having to roll our own thread ids.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
This undoes the niche optimization: https://github.com/mitsuhiko/fragile/pull/18

**Comment by Nilstrieb** [comment]
`ThreadId` uses a `NonZeroU64` as well, keeping the niche

**Comment by Nilstrieb** [comment]
It does have the disadvantage of being a little bigger on 32 bit though.

**Comment by mitsuhiko** [comment]
Oh I missed that. I will reopen this for now but I'm not sure yet what the advantage of reusing the threadid from the stdlib is.

**Comment by Nilstrieb** [comment]
It makes the code a little simpler and avoids the need for having a custom thread_id module. But since it's a pretty simple module there isn't a huge benefit.

**Comment by Nilstrieb** [comment]
Do you think we should do this? I'd resolve the conflicts then. If not, I can close it

**Comment by mitsuhiko** [comment]
I’m probably in favor of not applying this. It makes the type bigger and I’m not convinced (yet at least) that using the thread ID from the stdlib is necessary. No need to resolve the conflicts but I will leave this open in case my opinion on this changes / gets changed :)

**Comment by Noratrieb** [comment]
closing to clean up my open PRs, if you still haven't changed your opinion it seems unlikely you would now

**Pull request closed without merging**
